export const items = [
  {
    id: "a",
    category: "Recruitment Website",
    title: "Fullstack App - MERN",
    title2: "MongoDB, Express, React, Node, REST API",
    // title3: "Private Github repo access available on request",
    info: "As part of a team, I developed a full-stack application using agile methodologies and technologies such as HTML, CSS, Bootstrap, Node, MongoDB, React, Express and JavaScript with pair programming. The application allows employers to browse and filter through the profiles of bootcamp graduates. Hosted on Render",
    livelink: "https://tda-graduates.onrender.com",
    reponame: "Frontend Repository",
    repolink: "https://github.com/PhantomQuad/TDA-frontend/",
    reponame2: "Backend Repository",
    repolink2: "https://github.com/PhantomQuad/TDA-backend/",
    backgroundColor: "#814A0E",
  },
  {
    id: "b",
    category: "Weather App",
    title: "7 Day Forecast",
    title2: "HTML, JavaScript, Bootstrap, CSS, 3rd Party API",
    info: "A user-friendly, weather forecasting tool that allows users to quickly and easily check the weather forecast for today and the next 7 days for any city. With a sleek and intuitive city search feature, this app seamlessly pulls live data from a reliable 3rd party API to provide accurate and up-to-date weather information. This app is perfect for anyone looking for a convenient and reliable way to plan their day or week.",
    livelink: "https://weather-app-hen6.onrender.com/",
    reponame: "Repository",
    repolink: "https://github.com/PhantomQuad/weather-app/",
    backgroundColor: "#FA6779",
  },
  {
    id: "c",
    category: "Social Site",
    title: "Create a social profile",
    title2: "React, JavaScript, CSS, Local storage",
    info: "The aim of this project was to produce a front end only social media stream that consist of a series of social card components displaying posts by a user. This app was built using React.",
    livelink: "https://project-social.onrender.com/",
    reponame: "Repository",
    repolink: "https://github.com/PhantomQuad/Project-Social/",
    backgroundColor: "#282F49",
  },
  {
    id: "d",
    category: "Adventure Game",
    title: "OOP Text based game",
    title2: "HTML, JavaScript, CSS",
    info: "I have created a text-based adventure game using JavaScript and object-oriented programming principles. The game consists of three classes: Room, Character, and Enemy. Each class has its own constructor and methods to create the game. The Room class represents rooms, Character class represents NPCs and the Enemy class represents enemies with weakness the player can exploit. The methods in the Room class allow navigation and the methods in Character class allow interaction with NPCs.",
    livelink: "https://phantomquad.github.io/Project-Game/",
    reponame: "Repository",
    repolink: "https://github.com/PhantomQuad/Project-Game/",
    backgroundColor: "#959684",
  },
  {
    id: "e",
    category: "The Fitness Quiz?",
    title: "Multiple choice quiz",
    title2: "HTML, JavaScript, Bootstrap, CSS",
    info: "This code is a JavaScript quiz website using Bootstrap. It has functions for starting the quiz, navigating questions, calculating results, and displaying them. The introduction screen is hidden when the quiz starts and questions are displayed. The user's answers are used to calculate a score and a result message is displayed based on the score.",
    livelink: "https://phantomquad.github.io/Project-JS-Quiz/",
    reponame: "Repository",
    repolink: "https://github.com/PhantomQuad/Project-JS-Quiz/",
    backgroundColor: "#5DBCD2",
  },
  {
    id: "f",
    category: "Ceaser Cipher",
    title: "Encode and decode text strings",
    title2: "HTML, JavaScript, Bootstrap, CSS",
    info: "This Caesar Cipher project uses Bootstrap and JavaScript to convert user's message based on chosen encryption/decryption and key values.",
    livelink: "https://phantomquad.github.io/Project-Cipher/",
    reponame: "Repository",
    repolink: "https://github.com/PhantomQuad/Project-Cipher/",
    backgroundColor: "#8F986D",
  },
];

export const openSpring = { type: "spring", stiffness: 200, damping: 30 };
